name: Build and Release

on:
  release:
    types: [created]
  push:
    branches:
      - main
      - parallel_build

env:
  PYTHONUNBUFFERED: 1

# Cancel redundant builds on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wads:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bash -x .github/scripts/install_deps.sh
    - name: Build wads
      run: |
        export PATH="/tmp/qpakman:/tmp/fteqcc:/tmp/ericw-tools:$PATH"
        python build.py --compile-wads
    - name: Upload texture-wads-artifact
      uses: actions/upload-artifact@v4
      with:
        name: texture-wads-artifact
        path: ./texture-wads/*.wad

  build_progs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bash -x .github/scripts/install_deps.sh
    - name: Build progs
      run: |
        export PATH="/tmp/qpakman:/tmp/fteqcc:/tmp/ericw-tools:$PATH"
        python build.py --compile-progs
    - name: Upload progs-artifact
      uses: actions/upload-artifact@v4
      with:
        name: progs-artifact
        path: lq1/progs.dat

  build_maps:
    needs: build_wads
    runs-on: ubuntu-latest
    strategy:
      matrix:
        map_dir: [brushmodels, dm, e0, e1, e2, e3, e4, misc, prefabs]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bash -x .github/scripts/install_deps.sh
    - name: Download texture-wads-artifact
      uses: actions/download-artifact@v4
      with:
        name: texture-wads-artifact
        path: ./texture-wads
    - name: Build maps
      run: |
        export PATH="/tmp/qpakman:/tmp/fteqcc:/tmp/ericw-tools:$PATH"
        cd lq1/maps
        python compile_maps.py -d src/${{ matrix.map_dir }}
    - name: Upload maps-artifact
      uses: actions/upload-artifact@v4
      with:
        name: maps-artifact-${{ matrix.map_dir }}
        path: ./lq1/maps/*.{bsp,lit}

  assemble_releases:
    needs: [build_wads, build_progs, build_maps]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download texture-wads-artifact
      uses: actions/download-artifact@v4
      with:
        name: texture-wads-artifact
        path: ./texture-wads
    - name: Download progs-artifact
      uses: actions/download-artifact@v4
      with:
        name: progs-artifact
        path: ./lq1/progs.dat
    - name: Download maps-artifact-brushmodels
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-brushmodels
        path: ./lq1/maps/
    - name: Download maps-artifact-dm
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-dm
        path: ./lq1/maps/
    - name: Download maps-artifact-e0
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-e0
        path: ./lq1/maps/
    - name: Download maps-artifact-e1
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-e1
        path: ./lq1/maps/
    - name: Download maps-artifact-e2
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-e2
        path: ./lq1/maps/
    - name: Download maps-artifact-e3
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-e3
        path: ./lq1/maps/
    - name: Download maps-artifact-e4
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-e4
        path: ./lq1/maps/
    - name: Download maps-artifact-misc
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-misc
        path: ./lq1/maps/
    - name: Download maps-artifact-prefabs
      uses: actions/download-artifact@v4
      with:
        name:  maps-artifact-prefabs
        path: ./lq1/maps/
    - name: Build releases
      run: |
        ls -alh texture-wads
        ls -alh lq1
        ls -alh lq1/maps/
        python build.py --build

#   build_release:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Install dependencies
#       run: bash -x .github/scripts/install_deps.sh
#     - name: Build release artifacts
#       env:
#         PYTHONUNBUFFERED: 1
#       run: |
#         export PATH="/tmp/qpakman:/tmp/fteqcc:/tmp/ericw-tools:$PATH"
#         python build.py
#     - name: Zip artifacts
#       run: |
#         cd releases
#         zip -r full.zip full
#         zip -r mod.zip mod
#         zip -r lite.zip lite
#         zip -r mod_lite.zip mod_lite
#         zip -r dev.zip dev
#         cd ..
#     - name: Make artifact available on non-release pipelines
#       if: github.event_name != 'release'
#       uses: actions/upload-artifact@v4
#       with:
#         name: full.zip
#         path: releases/full.zip
#         retention-days: 14
#     - name: Upload asset full.zip
#       if: github.event_name == 'release'
#       uses: actions/upload-release-asset@v1
#       env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ github.event.release.upload_url }}
#         asset_path: releases/full.zip
#         asset_name: full.zip
#         asset_content_type: application/zip
