name: Build release

on:
  push:

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependecies
      run: bash -x install_deps.sh
    - name: Build release
      env:
        PYTHONUNBUFFERED: 1
      run: |
        export PATH="/tmp/qpakman:/tmp/fteqcc:/tmp/ericw-tools:$PATH"
        python build.py
        - name: Package Directories and Upload
    - name: Tar and upload
      run: |
        cd releases
        tar -czf full.tar.gz full
        tar -czf mod.tar.gz mod
        tar -czf dev.tar.gz dev
        cd ..
    - name: Upload full
      uses: actions/upload-artifact@v2
      with:
        name: full-artifact
        path: releases/full.tar.gz
    - name: Upload mod
      uses: actions/upload-artifact@v2
      with:
        name: mod-artifact
        path: releases/mod.tar.gz
    - name: Upload dev
      uses: actions/upload-artifact@v2
      with:
        name: dev-artifact
        path: releases/dev.tar.gz