name: Build release

on:
  push:


permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependecies
      run: source cibuild.sh
    - name: Build release
      run: python build.py
