name: Build and Release

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bash -x .github/scripts/install_deps.sh
    - name: Build release
      env:
        PYTHONUNBUFFERED: 1
      run: |
        export PATH="/tmp/qpakman:/tmp/fteqcc:/tmp/ericw-tools:$PATH"
        python build.py
    - name: Zip artifacts
      run: |
        cd releases
        zip -r full.zip full
        zip -r mod.zip mod
        zip -r lite.zip lite
        zip -r mod_lite.zip mod_lite
        zip -r dev.zip dev
        cd ..

  upload_assets:
    runs-on: ubuntu-latest
    needs: build_release
    if: github.event_name == 'release'
    strategy:
      matrix:
        file: [full.zip, mod.zip, lite.zip, mod_lite.zip, dev.zip]
    steps:
    - uses: actions/checkout@v3
    - name: Upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: releases/${{ matrix.file }}
        asset_name: ${{ matrix.file }}
        asset_content_type: application/zip
