name: Build release

on:
  release:
    types: [created]

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependecies
      run: bash -x .github/scripts/install_deps.sh
    - name: Build release
      env:
        PYTHONUNBUFFERED: 1
      run: |
        export PATH="/tmp/qpakman:/tmp/fteqcc:/tmp/ericw-tools:$PATH"
        python build.py
    - name: Zip
      run: |
        cd releases
        zip -r full.zip full
        zip -r mod.zip mod
        zip -r dev.zip dev
        cd ..
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: releases/full.zip
        asset_name: full.zip
        asset_content_type: application/zip
#    - name: Upload full
#      uses: actions/upload-artifact@v4
#      with:
#        name: full-artifact
#        path: releases/full.zip
#    - name: Upload mod
#      uses: actions/upload-artifact@v4
#      with:
#        name: mod-artifact
#        path: releases/mod.zip
#    - name: Upload dev
#      uses: actions/upload-artifact@v4
#      with:
#        name: dev-artifact
#        path: releases/dev.zip
